version: '3'

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${redis_secret}
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    command: ["redis-server", "--requirepass", "2123" ]

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  sops:
    image: mozilla/sops:latest
    command: ["sops", "--config", "/secrets/sops.yaml", "--decrypt", "/secrets/secrets.dev.yaml"]
    volumes:
      - "./secrets:/secrets"
    environment:
      SOPS_AGE_KEY_FILE: /secrets/keys.txt

volumes:
  redis-insight:
