version: '3.6'

services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pythonAPI
    restart: always
    ports:
      - "5000:5000"  
    links: 
      - influxdb
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8.10-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=DHBW_Blickbox
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    ports:
      - "8086:8086"  
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links: 
      - influxdb
    ports:
      - "3000:3000"  
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  influxdb_data:  