# creation rules are evaluated sequentially, the first match wins
creation_rules:
    # upon creation of a file that matches the pattern *.dev.yaml,
    # KMS set A as well as PGP and age is used
    - path_regex: \.dev\.yaml$
      age: 'age1qtqxa0rutdhfs0kunh9nja3jg999qq3adjjs0r09j9l0apvym5psdh5vc6'
    - path_regex: \.dev\.enc\.env$
      age: 'age1qtqxa0rutdhfs0kunh9nja3jg999qq3adjjs0r09j9l0apvym5psdh5vc6'
