version: '3.6'

services:
  valentin:
    build:
      context: ./client/valentin
      dockerfile: Dockerfile
    restart: always
  python_app:
    build:
      context: ./deployment/
      dockerfile: Dockerfile
    restart: always
    links: 
      - influxdb
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8.10-alpine
    container_name: influxdb
    restart: always

    environment:
      - INFLUXDB_DB=DHBW_Blickbox
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=
    links: 
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
  reverse-proxy:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped

    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  grafana_data:
  influxdb_data:  
  data:
  letsencrypt:


