version: '3.6'

services:

  sops:
    image: mozilla/sops:latest
    volumes:
      - "./secrets:/secrets"
    environment:
      SOPS_AGE_KEY_FILE: /secrets/key.txt
    command: >
      sh -c "sops --config /secrets/.sops.yaml --decrypt /secrets/secrets.dev.enc.env
      > /secrets/secrets.dev.env && chmod 600 /secrets/secrets.dev.env"
      
  valentin: 
    build:
      context: ./client/valentin
      dockerfile: Dockerfile
    restart: always 

  python_app:
    build:
      context: ./deployment/
      dockerfile: Dockerfile
    restart: always
    links: 
      - influxdb
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8.10-alpine
    container_name: influxdb
    env_file:
        - path: ./secrets/secrets.dev.env
          required: false
    volumes:
      - influxdb_data:/var/lib/influxdb
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    restart: always
    env_file:
        - path: ./secrets/secrets.dev.env
          required: false  
    links: 
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  reverse-proxy:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
        - path: ./secrets/secrets.dev.env
          required: false 
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}" ]


volumes:
  grafana_data:
  influxdb_data:  
  data:
  letsencrypt:


