site_name: 'IoT Blickbox Dokumentation'
theme: 'material'

nav:
  - Zusammenfassung: index.md
  - Dokumentation: Dokumentation/documentation.md
  - Setup: dev-journey/setup.md
  - Testing: dev-journey/test.md
