site_name: 'IoT Blickbox Dokumentation'
theme: 'readthedocs'

nav:
  - Zusammenfassung: index.md
  - Dokumentation: Dokumentation/documentation.md
  - Developer Journey:
    - Setup: dev-journey/setup.md
    - Testing: dev-journey/test.md


