; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[options]
platform = nordicnrf52
board = nano33ble
framework = arduino
unittesting_buildflag = 
	-std=gnu++11
	-D unitTesting 
generic_hw_buildflag = -D generic_hw
coverage_buildflag = 
	-lgcov
	--coverage
	-fprofile-abs-path
	-Og
test_framework = unity
selected_tests = *

[env:native_selected_unittests]
platform = native
check_tool = clangtidy
build_flags = 
	-D unity_testing
	-std=c++11  ; Verwende den C++17 Standard
	-I include
lib_deps = 
	- SaraLIB
	- LibStubs
test_framework = ${options.test_framework}
check_flags =
  clangtidy: --checks=-*,cert-*,clang-analyzer-* --fix


[env:ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
lib_deps = 
	SerialLogger
	SaraBLE
	SaraLIB
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
	sparkfun/SparkFun Weather Meter Kit Arduino Library@^1.1.1
	arduino-libraries/ArduinoBLE@^1.3.6
	powerbroker2/FireTimer@^1.0.5

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
	SerialLogger
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
	sparkfun/SparkFun Weather Meter Kit Arduino Library@^1.1.1
	powerbroker2/FireTimer@^1.0.5
	fabiobatsilva/ArduinoFake@^0.4.0
